# Generated by Django 4.2.6 on 2024-05-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
    ]
