# Generated by Django 4.2.6 on 2024-05-12 22:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0004_rename_bookings_tickets"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tickets",
            new_name="Ticket",
        ),
    ]
