# Generated by Django 4.2.6 on 2024-05-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0007_rename_ticket_type_ticket_trip_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="phone_number",
            field=models.CharField(default=89898989898, max_length=11),
            preserve_default=False,
        ),
    ]
