# Generated by Django 4.2.6 on 2024-05-13 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0008_users_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("location_id", models.IntegerField(primary_key=True, serialize=False)),
                ("loc_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("wallet_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "wallet_balance",
                    models.DecimalField(decimal_places=2, default=5000, max_digits=10),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
