# Generated by Django 4.2.6 on 2024-05-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0009_location_alter_ticket_price_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="return_date",
            field=models.DateField(default=None),
        ),
    ]
