# Generated by Django 4.2.6 on 2024-05-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0010_ticket_return_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="return_date",
            field=models.DateField(default=None, null=True),
        ),
    ]
