# Generated by Django 4.2.6 on 2024-05-28 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0012_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="number_of_tickets",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="return_date",
        ),
    ]
