# Generated by Django 4.2.6 on 2024-05-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0014_alter_users_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
