# Generated by Django 4.2.6 on 2024-05-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ticket", "0016_ticket_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="is_verified",
        ),
        migrations.AddField(
            model_name="users",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="verification_token",
            field=models.CharField(default=111111, max_length=6),
            preserve_default=False,
        ),
    ]
